site_name: LLM Best Practice
site_url: ""
theme:
  name: material

nav:
  - Home: index.md
  - NPU:
    # - 前言: NPU/intro.md
    - Atlas 300I Duo:
      - NPU驱动和固件安装: NPU/env.md
      - 离线安装Docker（国产银河麒麟V10系统 aarch64架构）: NPU/docker.md
      - 离线安装Miniforge Python环境: NPU/miniforge.md
      - 昇腾虚拟化实例（算力切分）: NPU/vnpu.md
      - MindIE单机单卡部署Qwen1.5-7B-Chat: NPU/llm.md
      - MindIE单机多卡部署Dolphin-72B-Chat: NPU/llm_parallel.md
      - （TODO）FastDeploy + vNPU 部署OCR模型: NPU/ocr.md
      - （TODO）MindIE + FastDeploy + vNPU 部署 7B + 0.5B + OCR: NPU/llm+vnpu.md
      - 常见问题解决: NPU/faq.md
  - Vector:
    - milvus:
      - 使用milvus完成私有化知识库搭建: Vector/milvus.md  
    # - MeiliSearch:
    #   - 使用MeiliSearch完成私有化知识库搭建: Vector/meili.md
  # - GPU:
  #   - Build Env: GPU/env.md
  # - Train: 
  #   - Pretrain: Train/Pretrain.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences