site_name: LLM Best Practice
site_url: ""
theme:
  name: material

nav:
  - Home: index.md
  - NPU:
    - 前言: NPU/intro.md
    - Atlas 300I Duo NPU驱动和固件安装: NPU/env.md
    - 国产银河麒麟V10系统 aarch64架构 离线安装Docker: NPU/docker.md
    - Atlas 300I Duo 离线安装Miniforge Python环境: NPU/miniforge.md
    - Atlas 300I Duo 昇腾虚拟化实例（算力切分）: NPU/vnpu.md
    - Atlas 300I Duo + Qwen2-0.5B-Chat + vNPU: NPU/llm.md
  - GPU:
    - Build Env: GPU/env.md
  - Train: 
    - Pretrain: Train/Pretrain.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences